### ISSUE TITLE
Whatever messages are going to users saying "don't upload test data to the live OSM server" aren't working.

### ISSUE THREAD

**Issue by SomeoneElseOSM** [metaodi/osmapi#66]
https://www.openstreetmap.org/changeset/44388695 is just the latest.

**Comment by metaodi** [comment]
This is a library, so there are no such messages. The "users" are developers. The assumption is, that they know what they are doing. Of course there will always be some that will test things on the wrong server, but  I don't know how we can change that.

Do you have a suggestion for a change?

**Comment by SomeoneElseOSM** [comment]
I'd suggest changing the "Note" section of the README to say that testing users should create a test account on the dev server and use that, just like the code example above on that page suggests.  What I'm guessing is happening now is that people try that example, discover that it doesn't work because they don't have an account on the dev server, and change the API URL that they're using.

It's still happening: https://www.openstreetmap.org/changeset/44933420 .

>  The "users" are developers. The assumption is, that they know what they are doing.

:)

I remember, not that long ago, that I was giving some training to some people about phone web app development (Phonegap).  I got to the bit about "now run this from the command line" and got blank looks all round - Command line? These "developers" had no idea of the concept...

**Comment by veeven** [comment]
One potential way of preventing API users testing on live OSM server is to change the API such that by default it connects to dev server.

**Comment by SomeoneElseOSM** [comment]
This is still a regularly recurring problem - for example https://www.openstreetmap.org/changeset/49384416 .

**Comment by metaodi** [comment]
@SomeoneElseOSM I updated the README (52101ce353d3ea431d5894e177781f4d0dd96f41), so that the "write to OSM" example now uses the DEV server. This should at least prevent those "My first test" changesets.

**Comment by metaodi** [comment]
I'm closing this for now.

**Comment by SomeoneElseOSM** [comment]
Still occasional rubbish getting added to the live server:
https://www.openstreetmap.org/changeset/51735660

**Comment by SomeoneElseOSM** [comment]
Still seeing the occasional one: https://www.openstreetmap.org/changeset/126994361 :)

**Comment by metaodi** [comment]
I added a comment to the latest example.

I'm really unsure how to prevent this. It's kind of the same as a user using the iD editor to test edit on PROD.

Maybe I should start to monitor for changesets using osmapi with the test comment. WDYT?

**Comment by SomeoneElseOSM** [comment]
Thanks for trying - maybe a link somewhere to https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct (if there isn't one that people should have read already) would help?

**Comment by metaodi** [comment]
It's already in the README: https://github.com/metaodi/osmapi#note

Maybe I should add a check to prevent changesets with the comment "My first test", so at least a warning is displayed to the developer. I'll think about it.

**Comment by SomeoneElseOSM** [comment]
Thanks!  We'll keep an eye out for any further issues (fingers crossed there won't be any).
